config/routes.rb
Rails.application.routes.draw do
 root "pages#home"
 get 'pages/home', to: 'pages#home'
# get '/books' , to: 'books#index'
 #get 'books/new' , to: 'books#new' , as: 'new_book'
 #get '/books/:id' , to: 'books#show' , as:'book'
 #post 'books', to: 'recipes#create'


 resources :books do
    resources :comments, only: [:create]
 end

 get '/signup', to: 'authors#new'
 resources :authors , except: [:new]

 get '/login', to: 'sessions#new'
 post '/login', to: "sessions#create"
 delete '/logout', to: "sessions#destroy"

 resources :genres, except: [:destroy]

 mount ActionCable.server => '/cable'
 get '/chat', to: 'chatrooms#show'
 resources :messages, only: [:create]


end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :book_genres
  has_many :books, through: :book_genres
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  before_action :set_genre, only: [:edit, :update, :show]
  before_action :require_admin, except: [:show, :index]
  
  
  def new
    @genre = Genre.new
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "Genre was created successfully"
      redirect_to genre_path(@genre)
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @genre.update(genre_params)
      flash[:success] = "Genre name was updated successfully"
      redirect_to @genre
    else
      render 'edit'
    end
  end
  
  def show
    @genre_books = @genre.books.paginate(page: params[:page], per_page: 5)
    
  end
  
  def index
    @genres = Genre.paginate(page: params[:page], per_page: 5)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
  
  def set_genre
    @genre = Genre.find(params[:id])
  end
  
  def require_admin
    if !logged_in? || (logged_in? and !current_author.admin?)
      flash[:danger] = "Only admin users can perform that action"
      redirect_to genres_path
    end
  end
  
end

app/views/genres/_form.html.erb
<%= render 'shared/errors' , obj: @genre %>

<div class = "row">
	<div class = "col-md-12">
		<%= form_for(@genre, :html => {class: "form-horizontal" , role: "form"}) do |f| %>
		  <div class = "form-group">
		  	<div class = "control-label col-md-2">
		  		<%=f.label :name%>
		  	</div>
		  	<div class = "col-md-8">
		  		<%= f.text_field :name , class: "form-control" , placeholder: "Enter Genre", autofocus: true %>
		  	</div>
		  </div>
		  <div class = "form-group">
		  	<div class = "col-md-offset-2 col-md-10">
		  		<%= f.submit(@genre.new_record? ? "Add Genre" : "Update Genre",
                          class: "btn btn-primary btn-lg btn-xlarge") %>
		  	</div>
		  </div>
        <% end %>
        <div class="col-md-4 col-md-offset-4 colormatch">
         [ <%= link_to "Cancel request and return to books listing",  books_path %> ]
        </div>
    </div>
</div>

app/views/genres/_genre.html.erb
<span class="badge  progress-bar-info"><%= link_to genre.name, genre_path(genre) %> &nbsp;  </span>

app/views/genres/edit.html.erb
<%= render 'shared/page_title', title: "Edit Genre name" %>

<%= render 'form' %>

app/views/genres/index.html.erb
<div class="heading"><%= render 'shared/page_title', title: "Available Genres" %></div>

<div align="center">
  <!--<%= will_paginate %> -->
  <% @genres.each do |gen| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="author-title"><%= link_to gen.name.capitalize,  genre_path(gen) %></li>
          <li><small><%= pluralize(gen.books.count, "drabble") if gen.books %></small></li>
          <% if logged_in? and current_author.admin?%>
             <li><%= link_to "Edit this Genre", edit_genre_path(gen)%></li>
          <% end%>
        </div>
      </div>
    </ul>      
  <% end %>
  <%= will_paginate %>
</div>

app/views/genres/new.html.erb
<%= render 'shared/page_title', title: "Enter a new Genre" %>

<%= render 'form' %>

app/views/genres/show.html.erb
<div class="heading"><%= render 'shared/page_title', title: "#{@genre.name}" %></div>


<% if @genre.books.count !=0 %> 
 <!-- <h4 align="center">Drabbles containing <%= @genre.name %></h4> 

  <div align="center">
    <%= will_paginate @genre_books %>
  </div> -->

  <%= render 'books/book', obj: @genre_books %>

  <div align="center">
    <%= will_paginate @genre_books %>
  </div>
<% else %>
  <h4 align = "center">No drabbles yet </h4>
<% end %>