config/routes.rb
Rails.application.routes.draw do
 root "pages#home"
 get 'pages/home', to: 'pages#home'
# get '/books' , to: 'books#index'
 #get 'books/new' , to: 'books#new' , as: 'new_book'
 #get '/books/:id' , to: 'books#show' , as:'book'
 #post 'books', to: 'recipes#create'


 resources :books do
    resources :comments, only: [:create]
 end

 get '/signup', to: 'authors#new'
 resources :authors , except: [:new]

 get '/login', to: 'sessions#new'
 post '/login', to: "sessions#create"
 delete '/logout', to: "sessions#destroy"

 resources :genres, except: [:destroy]

 mount ActionCable.server => '/cable'
 get '/chat', to: 'chatrooms#show'
 resources :messages, only: [:create]


end

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1> Welcome to Drabble-Reads </h1>
<h2> Your one stop to read drabbles !!! </h2>
<p><%= link_to "SIGN UP !!!", signup_path, class: " btn btn-lg glow-on-hover " %></p>
</div>


<div class="row">
  <div class="col-lg-4">
    <h2 class="heading">Authors!</h4>
    <p class="text-danger">An author is the writer of a book, article, play, or mostly written work.</p> <p> A broader definition of the word "author" states:"An author is "the person who originated or gave existence to anything" and whose authorship determines responsibility for what was created."</p> <p>Typically, the first owner of a copyright is the person who created the work, i.e. the author. If more than one person created the work (i.e., multiple authors), then a case of joint authorship takes place.Authors may portion out different rights they hold to different parties, at different times, and for different purposes or uses.
    </p>
    <p><%= link_to "View Authors >>", authors_path, class:"btn btn-primary btn-lg" %> </p>
  </div>
  <div class="col-lg-4">
    <h2 class="heading">Drabbles!!</h2>
    <p class="text-danger"> Drabble is a short work of fiction of precisely one hundred words in length.The purpose of the drabble is brevity, testing the author's ability to express interesting and meaningful ideas in a confined space.</p>
    <p>The concept is said to have originated in UK science fiction fandom in the 1980s; the 100-word format was established by the Birmingham University SF Society, taking a term from Monty Python's 1971 Big Red Book.</p><p> Drabbles come in two kinds; one that is exactly 100 words, no more, no less. Now, the other kind of drabble is more than 200 words, upto 1000 words, though they are commonly written to be 900 to 1000 words. </p>
    <p ><%= link_to "View Drabbles >>", books_path ,class: "btn btn-primary btn-lg"%></p>
 </div>
  <div class="col-lg-4">
    <h2 class="heading">Genres!!!</h2>
    <p class="text-danger">What Are Book Genres? Every work of literature can be divided into a genre with its own elements, tone, style, and storytelling devices. </p>
    <p>Every reader has preferences for books, and all of them fall into genres or sub-genres. Whether you are interested in dystopian, young adult, sci-fi, self-help, or historical fiction books, you probably prefer certain genres.</p>
    <p>A genre refers to the types of books that fall into that category. They are categorized by their style, tone, time period, target audience, and numerous other factors. These are the factors that differentiate fiction from nonfiction.</p>
    <p><%= link_to "View Genres >>", genres_path , class:"btn btn-primary btn-lg" %></p>
  </div>
</div>