config/routes.rb
Rails.application.routes.draw do
 root "pages#home"
 get 'pages/home', to: 'pages#home'
# get '/books' , to: 'books#index'
 #get 'books/new' , to: 'books#new' , as: 'new_book'
 #get '/books/:id' , to: 'books#show' , as:'book'
 #post 'books', to: 'recipes#create'


 resources :books do
    resources :comments, only: [:create]
 end

 get '/signup', to: 'authors#new'
 resources :authors , except: [:new]

 get '/login', to: 'sessions#new'
 post '/login', to: "sessions#create"
 delete '/logout', to: "sessions#destroy"

 resources :genres, except: [:destroy]

 mount ActionCable.server => '/cable'
 get '/chat', to: 'chatrooms#show'
 resources :messages, only: [:create]


end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true , length: { minimum: 5 , maximum: 5000}

  belongs_to :author
  validates :author_id, presence: true
  default_scope -> { order(updated_at: :desc) }
  has_many :book_genres
  has_many :genres, through: :book_genres
  has_many :comments, dependent: :destroy
  

end

app/controllers/books_controller.rb
class BooksController <ApplicationController

	before_action :set_book , only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@books = Book.paginate(page: params[:page], per_page: 5)
	end

	def show
		@comment = Comment.new
		@comments = @book.comments.paginate(page: params[:page], per_page: 5)
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.author = current_author  
		if @book.save
			flash[:success] = "Drabble was created successfully"
            redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @book.update(book_params)
			 flash[:success] = "Drabble was updated successfully!"
             redirect_to book_path(@book)
		else
			render 'edit'
		end
	end

	def destroy
		Book.find(params[:id]).destroy
		flash[:success] = "Drabble deleted successfully!"
		redirect_to books_path
	end

	private


	   def set_book
	   	@book = Book.find(params[:id])
	   end

	   def  book_params
	   	params.require(:book).permit(:name, :description, genre_ids: [])
       end

       def require_same_user
        if current_author != @book.author and !current_author.admin?
          flash[:danger] = "You can only edit or delete your own drabble"
          redirect_to books_path
        end  
       end

end

app/views/books/_book.html.erb
<% obj.each do |book| %>
  <div class="row">
  	<div class="col-md-2">
  		<section class="author_info center">
        <%= link_to gravatar_for(book.author, size: 120)  , author_path(book.author) %> 			
  		</section>
  	</div>
  	<div class="col-md-8 well ">
  	 <h4 class="heading"> <%= link_to book.name, book_path(book) %></h4>
     <p> <%= truncate(book.description , length: 150) %> </p>
     <% if book.genres.any? %>
       <p>Genres: <%= render book.genres %></p>
     <% end %>
     <p>
      <span class="quiet"><small>Created <%= time_ago_in_words(book.created_at) %> ago by <%= book.author.authorname.capitalize %>
                                                  | <%= pluralize(book.comments.count, 'Comment') %></small> </span>
     </p>
     <% if logged_in? && (current_author == book.author || current_author.admin?) %>
        <div class="book-actions">
          <%= link_to "Edit this drabble", 
                      edit_book_path(book), 
                              class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this drabble", book_path(book),  method: :delete,
                       data: { confirm: "The Drabble and their associated comments will be deleted permanently from this site.Are you sure you want to delete this drabble?" },class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>


<% end %>

app/views/books/_form.html.erb
<%= render 'shared/errors' , obj: @book %>

<div class = "row">
	<div class = "col-md-12">
		<%= form_for(@book, :html => {class: "form-horizontal" , role: "form"}) do |f| %>
		  <div class = "form-group">
		  	<div class = "control-label col-md-2">
		  		<%=f.label :name%>
		  	</div>
		  	<div class = "col-md-8">
		  		<%= f.text_field :name , class: "form-control" , placeholder: "Name of the Drabble", autofocus: true %>
		  	</div>
		  </div>
		  <div class = "form-group">
		  	<div class = "control-label col-md-2">
		  		<%=f.label :drabble%>
		  	</div>
		  	<div class = "col-md-8">
		  		<%= f.text_area :description, rows:10 , class: "form-control" , placeholder: "Enter the Drabble"%>
		  	</div>
		  </div>
		  <div class="form-group">
            <div class="row">
              <div class="col-md-offset-2 col-md-8">
                <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                <% end %>
              </div>
            </div>
          </div>
		  <div class = "form-group">
		  	<div class = "col-md-offset-2 col-md-10">
		  		<!--<%= f.submit class:"btn btn-primary btn-lg btn-xlarge" %> -->
		  		<%= f.submit(@book.new_record? ? "Create Drabble" : "Update Drabble", class:"btn btn-primary btn-lg btn-xlarge") %>
		  	</div>
		  </div>
        <% end %>
        <div class="col-md-4 col-md-offset-4 colormatch">
         [ <%= link_to "Cancel request and return to drabbles listing",  books_path %> ]
        </div>
    </div>
</div>

app/views/books/edit.html.erb
<%= render 'shared/page_title' , title: "Edit an existing drabble" %>

<%= render 'form' %>

app/views/books/index.html.erb
<div class="heading">
<h1 align="center"> Listing All Drabbles </h1>
<hr/>
</div>

<!--<div align="center">
  <%= will_paginate %>
</div> -->

<%= render 'book' , obj: @books %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/books/new.html.erb
<%= render 'shared/page_title' , title: "Create a new Drabble" %>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="heading"><%= render 'shared/page_title', title: @book.name %></div>

<div class="well col-md-8 col-md-offset-2 row">
  <h4 class="center description "><strong>Drabble </strong></h4>
  <hr />
  <%= simple_format(@book.description) %>
  <hr />
  <% if @book.genres.any? %>
    <p>Genres: <%= render @book.genres %></p>
  <% end %>
  <hr />
  <div class="pull-right">
    <p class="center">
      <em>Authored by:</em>
    </p>
    <p class = "center">
      <%= link_to gravatar_for(@book.author), author_path(@book.author) %>
    </p>
    <p class = "center">
       <%= @book.author.authorname.capitalize %>
      <!--<div class ="pull-right"><%= time_ago_in_words(@book.created_at) %> ago</div> -->
    </p>
    <p>
      <!--<small><%= @book.author.authorname %></small>-->
      <div class= "pull-right">authored: <%= time_ago_in_words(@book.created_at) %> ago
      </div>
    </p>
  </div>
  <div class="book-actions">
    <% if logged_in? && (current_author == @book.author || current_author.admin?) %>
      <%= link_to "Edit this drabble" , edit_book_path(@book) , class: "btn btn-xs btn-warning" %>
      <%= link_to "Delete this drabble", book_path(@book), method: :delete, data: { confirm: "This drabble and their respective comments will be deleted permanently.Are you sure you want to delete?"}, class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "Return to drabbles listing", books_path , class: "btn btn-xs btn-primary" %>
  </div>  
  </div>
</div>

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr />
      <%= form_for([@book, @comment], remote: true, :html => {class: "form-horizontal", 
                                                role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description, "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr />
    </div>
  </div>
<% end %>

<% if @book.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>