config/routes.rb
Rails.application.routes.draw do
 root "pages#home"
 get 'pages/home', to: 'pages#home'
# get '/books' , to: 'books#index'
 #get 'books/new' , to: 'books#new' , as: 'new_book'
 #get '/books/:id' , to: 'books#show' , as:'book'
 #post 'books', to: 'recipes#create'


 resources :books do
    resources :comments, only: [:create]
 end

 get '/signup', to: 'authors#new'
 resources :authors , except: [:new]

 get '/login', to: 'sessions#new'
 post '/login', to: "sessions#create"
 delete '/logout', to: "sessions#destroy"

 resources :genres, except: [:destroy]

 mount ActionCable.server => '/cable'
 get '/chat', to: 'chatrooms#show'
 resources :messages, only: [:create]


end

app/views/layouts/_footer.html.erb
<!--<footer class="footer">
  <small>
    <strong>The world belongs to those who read...</strong>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
    </ul>
  </nav>
</footer>-->

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-dark">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Drabble-Reads", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="color-me"><%= link_to "Authors", authors_path %></li>
        <li class="color-me"><%= link_to "All Drabbles", books_path %></li>
        <% if logged_in? %>
        <li class="color-me"><%= link_to "Author-Space", chat_path %></li>
        <li class="dropdown color-me">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Drabbles <span class="caret"></span></a>
          <ul class="dropdown-menu scn">
            <li><%= link_to "Create a new drabble", new_book_path %></li>
            <!--<li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li> -->
          </ul>
        </li>
        <% end %>
        <li class="dropdown color-me">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Genres <span class="caret"></span></a>
          <ul class="dropdown-menu sc overflow-auto p-3 bg-light" style="max-height: 300px;">
            <li><%= link_to "List All Genres", genres_path %></li>
            <li role="separator" class="divider"></li>
            <% Genre.all.each do |genre| %>
              <li><%= link_to genre.name.capitalize, genre_path(genre) %></li>
            <% end %>
            <% if logged_in? && current_author.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Add New Genre", new_genre_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
         <!-- <input type="text" class="form-control" placeholder="Search">-->
        </div>
        <!-- <button type="submit" class="btn btn-default">Submit</button>-->
      </form>
      <ul class="nav navbar-nav navbar-right scn">
        <% if logged_in? %>
        <li class="dropdown color-me">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_author.authorname.capitalize %>'s Profile <%= "Admin" if current_author.admin? %>
            <span class="caret"></span></a>
            <ul class="dropdown-menu color-log">
              <li><%= link_to "View your profile", 
                                author_path(current_author) %></li>
              <li><%= link_to "Edit your profile", 
                                edit_author_path(current_author) %></li>
              <!--<li><a href="#">Something else here</a></li>-->
              <!--<li role="separator" class="divider"></li>-->
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, 
                                      method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path , class: "navbar-brand", id: "logo"%></li>  
        <% end %>
      </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funreads</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>